language: python
dist: xenial
python:
  - 3.5
script:
  - java -version
  - echo $PATH
  - /usr/local/lib/jvm/openjdk11/bin/java -version
  - /usr/bin/java -version
  - source ./jdk_switcher.sh
  - jdk_switcher use openjdk8
  - source ./custom_path.sh
  - export PATH=$(get_filtered_path /usr/local/lib/jvm/openjdk11/bin)
  - java -version
  - pytest test.py
