# bugs

language: python
dist: xenial
python:
  - 3.5
script:
  - sudo apt install openjdk-8-jdk
  - java -version
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - java -version
  - pytest test.py
